In [14]:
import os
import pandas as pd

In [15]:
#directories
working_directory = os.getcwd()
data_folder         = os.path.join(working_directory, "data"        )
intermediate_folder = os.path.join(working_directory, "intermediate")
results_folder      = os.path.join(working_directory, "results"     )

In [16]:
#import from CSV
dfTruckDataBySubareaID = pd.read_csv(os.path.join(intermediate_folder, r"TruckDataBySubAreaID.csv"))
dfTruckDataByDISTLRG = pd.read_csv(os.path.join(intermediate_folder, r"TruckDataByDISTLRG.csv"))
dfTruckDataSumForChecks =  pd.read_csv(os.path.join(intermediate_folder, r"TruckDataSumForChecks.csv"))

In [17]:
#check sums to make sure they match
display(dfTruckDataSumForChecks.sum())
display(dfTruckDataByDISTLRG.sum())
display(dfTruckDataBySubareaID.sum())

Unnamed: 0                                                            0
od_trip_counts_sum                                             39422616
od_trip_volume_sum                                       8848046.049443
num_records                                                    12506579
table                 ut-udot-adap-dev.streetlight_data.udot_commerc...
dtype: object

Unnamed: 0                                                     634337178
origin_distlrg                                                  939514.0
destination_distlrg                                             946004.0
mode_of_travel         TrucksTrucksTrucksTrucksTrucksTrucksTrucksTruc...
vehicle_weight         HeavyHeavyHeavyHeavyHeavyHeavyHeavyHeavyHeavyH...
day_type               1: Weekdays (Tu-Th)1: Weekdays (Tu-Th)1: Weekd...
day_part               2: Peak AM (6am-9am)2: Peak AM (6am-9am)2: Pea...
data_period            1. All year1. All year1. All year1. All year1....
od_trip_counts_sum                                              39422616
od_trip_volume_sum                                        8848046.049435
num_records                                                     12506579
dtype: object

Unnamed: 0                                                         6961568
origin_subareaid                                                   17375.0
destination_subareaid                                              17395.0
mode_of_travel           TrucksTrucksTrucksTrucksTrucksTrucksTrucksTruc...
vehicle_weight           HeavyHeavyHeavyHeavyHeavyHeavyHeavyHeavyHeavyH...
day_type                 1: Weekdays (Tu-Th)1: Weekdays (Tu-Th)1: Weekd...
day_part                 2: Peak AM (6am-9am)2: Peak AM (6am-9am)2: Pea...
data_period              1. All year1. All year1. All year1. All year1....
od_trip_counts_sum                                                39422616
od_trip_volume_sum                                          8848046.049434
num_records                                                       12506579
dtype: object

# Sub Area

In [18]:
#fill na with -1 meaning EXTERNALS (unmatched TAZs) will be given -1 SubArea
dfTruckDataBySubareaID = dfTruckDataBySubareaID.fillna(-1)
dfTruckDataBySubareaID

,Unnamed: 0,origin_subareaid,destination_subareaid,mode_of_travel,vehicle_weight,day_type,day_part,data_period,od_trip_counts_sum,od_trip_volume_sum,num_records
0,0,1.0,-1.0,Trucks,Heavy,1: Weekdays (Tu-Th),2: Peak AM (6am-9am),1. All year,27419,2289.573822,2491
1,1,-1.0,0.0,Trucks,Heavy,1: Weekdays (Tu-Th),2: Peak AM (6am-9am),1. All year,20364,1700.458854,2041
2,2,1.0,1.0,Trucks,Heavy,1: Weekdays (Tu-Th),2: Peak AM (6am-9am),1. All year,100925,8427.558917,36365
3,3,-1.0,1.0,Trucks,Heavy,1: Weekdays (Tu-Th),2: Peak AM (6am-9am),1. All year,20923,1747.137134,2910
4,4,-1.0,5.0,Trucks,Heavy,1: Weekdays (Tu-Th),2: Peak AM (6am-9am),1. All year,4532,378.436433,293
...,...,...,...,...,...,...,...,...,...,...,...
8339,1653,3.0,2.0,Trucks,Heavy,2: Weekend Day (Sa-Su),3: Mid-Day (9am-3pm),3. Dec-Feb,1,0.524400,1
8340,1654,4.0,5.0,Trucks,Medium,2: Weekend Day (Sa-Su),3: Mid-Day (9am-3pm),3. Dec-Feb,1,0.972000,1
8341,1655,5.0,2.0,Trucks,Medium,2: Weekend Day (Sa-Su),2: Peak AM (6am-9am),3. Dec-Feb,1,0.972000,1
8342,1656,2.0,4.0,Trucks,Medium,2: Weekend Day (Sa-Su),1: Early AM (12am-6am),3. Dec-Feb,1,0.972000,1
8343,1657,5.0,4.0,Trucks,Medium,2: Weekend Day (Sa-Su),1: Early AM (12am-6am),3. Dec-Feb,1,0.972000,1

In [34]:
dfTruckDataBySubareaID_Pivot_NumRecords = dfTruckDataBySubareaID.pivot_table(values="num_records",index=['day_type', 'day_part', 'data_period', 'origin_subareaid','vehicle_weight'], columns="destination_subareaid",)
dfTruckDataBySubareaID_Pivot_NumRecords = dfTruckDataBySubareaID_Pivot_NumRecords.fillna(0)
dfTruckDataBySubareaID_Pivot_NumRecords = dfTruckDataBySubareaID_Pivot_NumRecords.reset_index()
dfTruckDataBySubareaID_Pivot_NumRecords

destination_subareaid,day_type,day_part,data_period,origin_subareaid,vehicle_weight,-1.0,0.0,1.0,2.0,3.0,4.0,5.0
0,0: All Days (M-Su),0: All Day (12am-12am),1. All year,-1.0,Heavy,272.0,4784.0,7155.0,826.0,1131.0,514.0,639.0
1,0: All Days (M-Su),0: All Day (12am-12am),1. All year,-1.0,Medium,332.0,3635.0,6490.0,1027.0,1157.0,474.0,451.0
2,0: All Days (M-Su),0: All Day (12am-12am),1. All year,0.0,Heavy,3697.0,37545.0,28665.0,1321.0,2733.0,2222.0,3552.0
3,0: All Days (M-Su),0: All Day (12am-12am),1. All year,0.0,Medium,3791.0,58719.0,29845.0,1434.0,1484.0,1769.0,1558.0
4,0: All Days (M-Su),0: All Day (12am-12am),1. All year,1.0,Heavy,5582.0,28655.0,105908.0,4441.0,2068.0,3832.0,3415.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1255,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,3.0,Medium,23.0,6.0,7.0,0.0,99.0,0.0,11.0
1256,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,4.0,Heavy,41.0,51.0,98.0,2.0,3.0,51.0,6.0
1257,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,4.0,Medium,20.0,49.0,38.0,0.0,0.0,69.0,0.0
1258,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,5.0,Heavy,55.0,124.0,56.0,1.0,45.0,6.0,79.0
1259,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,5.0,Medium,34.0,20.0,17.0,0.0,13.0,0.0,34.0

In [35]:
dfTruckDataBySubareaID_Pivot_ODTripVolume = dfTruckDataBySubareaID.pivot_table(values="od_trip_volume_sum",index=['day_type', 'day_part', 'data_period', 'origin_subareaid','vehicle_weight'], columns="destination_subareaid",)
dfTruckDataBySubareaID_Pivot_ODTripVolume = dfTruckDataBySubareaID_Pivot_ODTripVolume.fillna(0)
dfTruckDataBySubareaID_Pivot_ODTripVolume = dfTruckDataBySubareaID_Pivot_ODTripVolume.reset_index()
dfTruckDataBySubareaID_Pivot_ODTripVolume

destination_subareaid,day_type,day_part,data_period,origin_subareaid,vehicle_weight,-1.0,0.0,1.0,2.0,3.0,4.0,5.0
0,0: All Days (M-Su),0: All Day (12am-12am),1. All year,-1.0,Heavy,5380.667260,4954.143288,6022.410740,194.710438,1282.624932,713.686849,1003.723151
1,0: All Days (M-Su),0: All Day (12am-12am),1. All year,-1.0,Medium,5360.047397,2861.008767,4018.354521,379.213151,756.628767,250.123562,484.801644
2,0: All Days (M-Su),0: All Day (12am-12am),1. All year,0.0,Heavy,4883.672548,7168.152904,3682.006356,128.657589,314.208986,184.473863,543.256849
3,0: All Days (M-Su),0: All Day (12am-12am),1. All year,0.0,Medium,2811.543288,33143.003014,5698.982466,191.670411,171.431507,247.460548,240.070685
4,0: All Days (M-Su),0: All Day (12am-12am),1. All year,1.0,Heavy,5897.416767,3734.015342,19243.001671,495.055151,151.465397,403.967589,343.948932
...,...,...,...,...,...,...,...,...,...,...,...,...
1255,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,3.0,Medium,28.800000,5.400000,6.300000,0.000000,141.300000,0.000000,10.800000
1256,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,4.0,Heavy,89.827778,28.162222,58.752222,0.971111,1.456667,29.618889,3.884444
1257,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,4.0,Medium,32.400000,65.700000,48.600000,0.000000,0.000000,81.900000,0.000000
1258,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,5.0,Heavy,204.904444,71.862222,30.590000,0.485556,27.676667,2.913333,44.185556
1259,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,5.0,Medium,68.400000,22.500000,22.500000,0.000000,16.200000,0.000000,88.200000

# Large District

In [36]:
dfTruckDataByDISTLRG = dfTruckDataByDISTLRG.fillna(-1)
display(dfTruckDataByDISTLRG.groupby(['origin_distlrg','vehicle_weight'],as_index=False).agg(od_trip_counts_sum=('od_trip_counts_sum','sum')))

    origin_distlrg vehicle_weight  od_trip_counts_sum
0             -1.0          Heavy             3759804
1             -1.0         Medium             1439584
2              1.0          Heavy             2972624
3              1.0         Medium             3226980
4              2.0          Heavy             1882372
5              2.0         Medium             2755276
6              3.0          Heavy              142164
7              3.0         Medium              576612
8              4.0          Heavy              546000
9              4.0         Medium             1325956
10             5.0          Heavy              408544
11             5.0         Medium              565844
12             6.0          Heavy                2060
13             6.0         Medium               10644
14             7.0          Heavy                1164
15             7.0         Medium                4008
16             8.0          Heavy              369892
17             8.0         Medium             1043292
18             9.0          Heavy              670932
19             9.0         Medium             1186732
20            10.0          Heavy                 492
21            10.0         Medium                 688
22            11.0          Heavy              237176
23            11.0         Medium              415316
24            12.0          Heavy             2152828
25            12.0         Medium             3513440
26            13.0          Heavy               12496
27            13.0         Medium              253040
28            14.0          Heavy              147728
29            14.0         Medium             2123984
30            15.0          Heavy               60652
31            15.0         Medium              556248
32            16.0          Heavy              125708
33            16.0         Medium             1703612
34            17.0          Heavy               70164
35            17.0         Medium              939236
36            18.0          Heavy                8300
37            18.0         Medium               29664
38            19.0          Heavy                4272
39            19.0         Medium              182796
40            20.0          Heavy               91900
41            20.0         Medium             1398160
42            21.0          Heavy               95904
43            21.0         Medium             1011828
44            22.0          Heavy              428880
45            22.0         Medium              888732
46            23.0          Heavy                4756
47            23.0         Medium               11776
48            24.0          Heavy                3180
49            24.0         Medium                3848
50            25.0          Heavy               33508
51            25.0         Medium               20192
52            26.0          Heavy                 184
53            26.0         Medium                1444

In [37]:
dfTruckDataByDISTLRG_Pivot_NumRecords = dfTruckDataByDISTLRG.pivot_table(values="num_records",index=['day_type', 'day_part', 'data_period', 'origin_distlrg','vehicle_weight'], columns="destination_distlrg",)
dfTruckDataByDISTLRG_Pivot_NumRecords = dfTruckDataByDISTLRG_Pivot_NumRecords.fillna(0)
dfTruckDataByDISTLRG_Pivot_NumRecords = dfTruckDataByDISTLRG_Pivot_NumRecords.reset_index()
dfTruckDataByDISTLRG_Pivot_NumRecords

destination_distlrg,day_type,day_part,data_period,origin_distlrg,vehicle_weight,-1.0,1.0,2.0,3.0,4.0,...,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0
0,0: All Days (M-Su),0: All Day (12am-12am),1. All year,-1.0,Heavy,272.0,4566.0,2452.0,489.0,1025.0,...,298.0,22.0,40.0,522.0,458.0,621.0,13.0,9.0,40.0,1.0
1,0: All Days (M-Su),0: All Day (12am-12am),1. All year,-1.0,Medium,332.0,3478.0,2078.0,545.0,1109.0,...,372.0,16.0,53.0,544.0,406.0,479.0,14.0,6.0,26.0,1.0
2,0: All Days (M-Su),0: All Day (12am-12am),1. All year,1.0,Heavy,3520.0,29696.0,11658.0,1164.0,3579.0,...,884.0,94.0,56.0,1382.0,1530.0,2938.0,37.0,62.0,354.0,10.0
3,0: All Days (M-Su),0: All Day (12am-12am),1. All year,1.0,Medium,3681.0,50527.0,14687.0,2517.0,6746.0,...,2182.0,90.0,277.0,2136.0,1653.0,2460.0,50.0,6.0,136.0,16.0
4,0: All Days (M-Su),0: All Day (12am-12am),1. All year,2.0,Heavy,1794.0,11453.0,12289.0,1302.0,1401.0,...,446.0,69.0,24.0,563.0,787.0,1364.0,17.0,27.0,163.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,22.0,Medium,27.0,16.0,9.0,3.0,4.0,...,1.0,0.0,1.0,4.0,12.0,40.0,0.0,0.0,1.0,0.0
4687,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,24.0,Heavy,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0
4688,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,24.0,Medium,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
4689,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,25.0,Heavy,6.0,6.0,4.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
4690,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,25.0,Medium,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0

In [38]:
dfTruckDataByDISTLRG_Pivot_ODTripVolume = dfTruckDataByDISTLRG.pivot_table(values="od_trip_volume_sum",index=['day_type', 'day_part', 'data_period', 'origin_distlrg','vehicle_weight'], columns="destination_distlrg",)
dfTruckDataByDISTLRG_Pivot_ODTripVolume = dfTruckDataByDISTLRG_Pivot_ODTripVolume.fillna(0)
dfTruckDataByDISTLRG_Pivot_ODTripVolume = dfTruckDataByDISTLRG_Pivot_ODTripVolume.reset_index()
dfTruckDataByDISTLRG_Pivot_ODTripVolume

destination_distlrg,day_type,day_part,data_period,origin_distlrg,vehicle_weight,-1.0,1.0,2.0,3.0,4.0,...,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0
0,0: All Days (M-Su),0: All Day (12am-12am),1. All year,-1.0,Heavy,5380.667260,4082.813178,4289.951178,193.309644,615.667151,...,52.763260,30.673808,2.765671,69.680548,105.095507,397.646055,1.544466,7.830082,58.222767,0.035918
1,0: All Days (M-Su),0: All Day (12am-12am),1. All year,-1.0,Medium,5360.047397,2234.601370,2106.443836,225.690411,581.801918,...,90.808767,3.927945,11.051507,187.875616,70.703014,292.998082,3.994521,0.932055,15.778356,0.066575
2,0: All Days (M-Su),0: All Day (12am-12am),1. All year,1.0,Heavy,4528.876438,5631.122137,1861.117151,109.764822,389.744137,...,61.060274,11.242274,3.017096,102.186164,109.441562,336.585781,2.873425,5.028493,54.020384,0.395096
3,0: All Days (M-Su),0: All Day (12am-12am),1. All year,1.0,Medium,2240.193699,16929.110959,4677.716712,798.637808,1098.493151,...,273.291781,8.122192,32.621918,326.219178,210.178356,464.829041,6.058356,0.732329,16.577260,1.930685
4,0: All Days (M-Su),0: All Day (12am-12am),1. All year,2.0,Heavy,3902.900877,1763.061534,2614.098082,183.791425,119.211205,...,26.794685,7.147644,1.041616,28.446904,54.918329,178.906603,1.005699,2.011397,30.278712,0.035918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,22.0,Medium,41.400000,19.800000,8.100000,2.700000,3.600000,...,0.900000,0.000000,1.800000,3.600000,13.500000,59.400000,0.000000,0.000000,0.900000,0.000000
4687,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,24.0,Heavy,0.485556,0.485556,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.456667,0.000000,0.000000,0.485556,0.000000
4688,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,24.0,Medium,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.800000,0.000000,0.000000,0.000000,0.000000
4689,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,25.0,Heavy,5.826667,2.913333,2.427778,0.000000,1.942222,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.971111,0.000000,0.000000,1.456667,0.000000
4690,2: Weekend Day (Sa-Su),5: Late PM (6pm-12am),5. Jun-Aug,25.0,Medium,3.600000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.900000,3.600000,0.000000,0.000000,0.000000,0.000000

# Export to CSV

In [33]:
dfTruckDataByDISTLRG_Pivot_ODTripVolume.to_csv(os.path.join(results_folder,r"dfTruckDataByDISTLRG_Pivot.csv"))